import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import BottomSheet from '@/components/BottomSheet';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <div className="px-5 py-10 pb-20">{children}</div>
                <BottomSheet />
            </body>
        </html>
    );
}
