import type { Metadata } from 'next';
import './globals.css';
import BottomNav from '@/components/BottomNav';
import { Toaster } from 'react-hot-toast';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <Toaster position="top-center" />
                <div className="overflow-hidden">{children}</div>
                <BottomNav />
            </body>
        </html>
    );
}
