import type { Metadata } from 'next';
import './globals.css';
import BottomNav from '@/components/BottomNav';
import { Toaster } from 'react-hot-toast';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    if (window?.Telegram) {
        window.Telegram.WebApp.ready();
        window.Telegram.WebApp.expand();
    }
    return (
        <html lang="en">
            <head>
                <script src="https://telegram.org/js/telegram-web-app.js"></script>
            </head>
            <body>
                <Toaster position="top-center" />
                <div className="overflow-hidden">{children}</div>
                <BottomNav />
            </body>
        </html>
    );
}
